name: Call a reusable workflow


on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-workflow:
    uses: sukolenvo/experimental-common-workflow/.github/workflows/commit/commit.yaml@master
